### ISSUE TITLE
[BUG] Results with Errors

### ISSUE THREAD

**Issue by munanadi** [Bonfida/sns-sdk#11]
I tried to use the `@bonfida/spl-name-service` package and tried running the example given in [here](https://sns.guide/installation.html#example)

```js
const connection = new Connection(clusterApiUrl("mainnet-beta"));
const owner = await resolve(connection, "bonfida");
expect(owner.toBase58()).toBe("HKKp49qGWXd639QsuH7JiLijfVW5UtCVY4s1n2HANwEA");
```

This runs but there is a error logged in the console as shown below
```sh
node index.js
Error: Invalid name account provided
    at G.retrieve (/Users/aadhi/Documents/github/bonfida-trial/node_modules/@bonfida/spl-name-service/dist/index.cjs:1:9672)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ue (/Users/aadhi/Documents/github/bonfida-trial/node_modules/@bonfida/spl-name-service/dist/index.cjs:1:15017)
    at async pe (/Users/aadhi/Documents/github/bonfida-trial/node_modules/@bonfida/spl-name-service/dist/index.cjs:1:15166)
    at async exports.resolve (/Users/aadhi/Documents/github/bonfida-trial/node_modules/@bonfida/spl-name-service/dist/index.cjs:1:23924)
    at async main (/Users/aadhi/Documents/github/bonfida-trial/index.js:11:17)
{
  owner: PublicKey [PublicKey(HKKp49qGWXd639QsuH7JiLijfVW5UtCVY4s1n2HANwEA)] {
    _bn: <BN: f26cb7227020209c2da674948f8f3c330ee4f9a386256bd14f37a6e0c567542b>
  }
} HKKp49qGWXd639QsuH7JiLijfVW5UtCVY4s1n2HANwEA
```

Looks like this is thrown from here
https://github.com/Bonfida/sns-sdk/blob/e0f96e21efd660ae64014e1a8bfa5d59f82227c7/js/src/utils.ts#L151-L161

Specifically the line 
```js
const result = _deriveSync(sub, parentKey);
```
produces a pubkey that doesn't exists.

`sub` however is `\x01SOL` which indeed matches with what is given in this [guide](https://sns.guide/domain-name/records.html#difference-between-records-and-subdomains) 

What could be causing the problem here? Can you please help me out?

**Comment by dr497** [comment]
Hi @munanadi! Thanks for opening this issue.

As far as I understand no error is being thrown by `resolve` with this example, it's simply logged. As you have rightly pointed out, the resolution of a domain involves checking if the `SOL` record exists or not. In the case of `bonfida.sol`, it does not exist and this information is logged on this [line](https://github.com/Bonfida/sns-sdk/blob/main/js/src/resolve.ts#L74) which produces the output you have put above.

I agree that it might be confusing to log the error this way and we should probably replace the information that is logged to make things clearer.

**Comment by munanadi** [comment]
@dr497 but the error is thrown from inside this
```js
const { registry, nftOwner } = await NameRegistryState.retrieve(...
```

**Comment by dr497** [comment]
You are right, `NameRegistryState.retrieve` throws this error but it's caught by `resolve` and logged instead of thrown.
