### ISSUE TITLE
[Bug] Slow loading images on a website

### ISSUE THREAD

**Issue by NikhilBhagoria** [Bonfida/sns-sdk#17]
-----Solution----------
images convert in webp format.

**Comment by dr497** [comment]
Which website and images are you referring to?

**Comment by NikhilBhagoria** [comment]
![image](https://github.com/Bonfida/sns-sdk/assets/123961691/e5b8c093-b006-47d6-963e-902e95ac87f4)
![image](https://github.com/Bonfida/sns-sdk/assets/123961691/b933f595-4f88-4914-8816-a3ba612b96bc)
 
WebSite: https://bonfida.org

**Comment by dr497** [comment]
Got it, thanks for letting us know. I will close the issue as it's unrelated to this repository.
