### ISSUE TITLE
How to use react useDomainOwner hook

### ISSUE THREAD

**Issue by alexandr-kazakov** [Bonfida/sns-sdk#57]
Any example please?

**Comment by akashrdev** [comment]
Hi @alexandr-kazakov - please see our docs: [useDomainsForOwner](https://sns.guide/domain-name/react-hooks/use-domains-for-user.html)

**Comment by alexandr-kazakov** [comment]
thanks, for some reason I couldn't find it.

**Comment by alexandr-kazakov** [comment]
Look, I asked about this lib https://github.com/Bonfida/sns-sdk/blob/main/react/README.md 
`npm install @bonfida/sns-react`

It has **useDomainOwner** hook, your docs doesn't have info about it, can you give me an example how I can use useDomainOwner hook in react please?

**Comment by akashrdev** [comment]
Oh my apologies, I misread the hook in question. The example below will log "HKKp49qGWXd639QsuH7JiLijfVW5UtCVY4s1n2HANwEA" which is the owner address of the "bonfida" domain. The initial return is of type Public Key, but using the .toBase58() method will give us the address as a string. 

`
  const { connection } = useConnection();
  const { data: domainOwner } = useDomainOwner(connection, "bonfida");

  console.log("domain owner:", domainOwner?.toBase58());
  `

If you need further assistance we have a dev-general channel on Discord where our team can assist. 

https://discord.gg/EVaEvGqv.

**Comment by akashrdev** [comment]
@alexandr-kazakov I'm going to close this issue. Please feel free to reach back out on here or on Discord if you need anything further.
