### ISSUE TITLE
useSubdomains() method return data undefined result

### ISSUE THREAD

**Issue by alexandr-kazakov** [Bonfida/sns-sdk#60]
``` javascript
import { useSubdomains } from '@bonfida/sns-react';

const { connection } = useConnection();
const subDomains = useSubdomains(connection, 'verified-iban');

console.log("subDomains: ", subDomains.data); // undefined
```

As I understand the **data** in subDomain fails to load sometimes and I get undefined instead of the array. How I can around of this? 

If the data has had time to load, I get the array in the data:

``` javascript
console.log("subDomains: ", subDomains.data); 
[
    "ch5204835012345671000",
    "ch9430700114900892402",
    "ch7200700114900892402",
    "li2430172110007062984"
]
```

**Comment by dr497** [comment]
Hi @alexandr-kazakov ! I tried to replicate the issue and it loaded very quickly for me. I suspect that might be due to the RPC you are using. Are you using a private RPC or a public one?

**Comment by alexandr-kazakov** [comment]
I'm using public RPC and I tried different public RPCs(for example helius & ironforge) and for all of them I have this issue. I don't know how to get around it.

**Comment by letehaha** [comment]
@alexandr-kazakov  tbh I understood your point a bit differently. Seems like you mean that initially the result is `undefined` and only after data is loaded the result becomes an array, and that bothers you. If that is correct, have you tried using it like that?

```ts
const { data: subdomains = [] } = useSubdomains(connection, 'verified-iban');

console.log("subDomains: ", subdomains); // this way you will always have an array here
```

**Comment by alexandr-kazakov** [comment]
@letehaha thank you for your reply, but you just change syntax, it doesn't help me.

My problem is next: sometimes the data has undefined value, or it can be a empty array it's doesn't matter, how I can check and track is useSubdomains(connection, 'verified-iban'); fully load list of subdomains? 

``` js
import { useSubdomains } from '@bonfida/sns-react';

const { connection } = useConnection();
const subDomains = useSubdomains(connection, 'verified-iban');

console.log("subDomains: ", subDomains.data); // undefined

```
How I can around it?

@dr497 answer is good, maybe it's RPC issue, but does this means I can't use public RPC with your lib or do you know another way to around this problem? 

Thanks

**Comment by dr497** [comment]
@alexandr-kazakov Public RPC on Solana sometimes disable certain methods (e.g `getProgramAccounts`) or have very strict rate limits which could explain why sometimes the data does not load. If you are considering building an app I would strongly recommend you to get your own private RPC, [Helius](https://www.helius.dev/) is very good and has an affordable pricing

**Comment by alexandr-kazakov** [comment]
It will be good somehow to wrap useSubdomains() method to Promise, like this:

``` js
new Promise((resolve,reject) => {
   return resolve(useSubdomains(connection, 'verified-iban'))
}).then((res) => {console.log('The data is fully loaded', res.data});
```

@dr497 can I make something like this? In this case I'll be know for sure that the data array list of subdomains is loaded

**Comment by letehaha** [comment]
@alexandr-kazakov actually you can simply check the implementation of `useSubdomains` [here](https://github.com/Bonfida/sns-sdk/blob/main/react/src/hooks/useSubdomains/index.tsx#L25).

```ts
import { getDomainKeySync, findSubdomains } from "@bonfida/spl-name-service";

const pubKey = getDomainKeySync(domain).pubkey;
const subdomains = pubKey ? await findSubdomains(connection, pubKey) : undefined;
```

`@bonfida/spl-name-service` is already a dependency so using it won't cause any bundle increase.

**Comment by alexandr-kazakov** [comment]
@letehaha thank you it's working for me well. 

But anyway, please think about how to update useSubdomains() method so the users can work with it and public RPCs and not have a problem like mine. Thanks
