### ISSUE TITLE
Changelog hasn't been updated from 0.1.26 -> 0.2.12

### ISSUE THREAD

**Issue by mikemaccana** [Bonfida/sns-sdk#8]
See https://sns.guide/changelog.html. I'm currently trying to update to the latest version and seeing 

> Module '"@bonfida/spl-name-service"' has no exported member 'getAllDomains'

But there's nothing in the Changelog to tell me what to fix.

**Comment by dr497** [comment]
The function `getAllDomains` has not been removed and is still exported from the packages https://github.com/Bonfida/sns-sdk/blob/main/js/src/utils.ts#LL184C23-L184C36

Could you share your `package.json` and `yarn.lock`?
