### ISSUE TITLE
Invalid export path in package.json

### ISSUE THREAD

**Issue by muckee** [Bonfida/sns-sdk#81]
The `react/package.json` file exports `./dist/index.csj`, where it should actually be `./dist/index.cjs`.

https://github.com/Bonfida/sns-sdk/blob/b14eb45420b8cab2cb49b2aac2e2313ad6827f56/react/package.json#L27

**Comment by akashrdev** [comment]
Hi, thanks so much for bringing this to our attention. We'll get this updated and reply here once the fix is live.

**Comment by akashrdev** [comment]
This has been fixed on version 3.1.1. I'll be closing this issue out now. If you need further assistance, please feel free to reach out again.
