### ISSUE TITLE
`transferSubdomain` does not work for PDA's

### ISSUE THREAD

**Issue by Sabnock01** [Bonfida/sns-sdk#90]
In the `transferSubdomain` function on the JS SDK, an initial call is made `NameRegistryState.retrieve()` [here](https://github.com/Bonfida/sns-sdk/blob/b5155a86adc3526d55a825cdf2eb2a8c02d4be5a/js/src/state.ts#L43-L46) which makes an RPC call to check that the account info exists for the name account. 

If one wants to create a PDA and transfer a subdomain to it either across two instructions in the same transaction or two bundled transactions, this check will fail and return `null` as the account doesn't exist yet. I would suggest removing this check or making an alternate `transferSubdomainUnsafe` function or the like which removes it.

**Comment by akashrdev** [comment]
Hi there @Sabnock01 - thank you for raising this issue. We'll look into this, and update you based on what we find and potential solutions as well.

**Comment by akashrdev** [comment]
Hi there @Sabnock01 as discussed on Discord, I'm glad you were able to come to a resolution using `transferInstruction`. I will go ahead and close this. Please feel free to reach back out if any further questions or concerns arise.
